sites:
  demo_portal:
    url_login: "login_page.html"
    username_selector: "#username"
    password_selector: "#password"
    login_button_selector: "#login-btn"
    url_success: "**/dashboard.html"
